Arpit | Artificial Neural Networks | Added README
NishkarshRaj/100DaysofMLCode pull request #55
Opened 2020-10-03 08:47 UTC by aceking007

#54 Added Documentation for Artificial Neural Networks in Deep Learning.

2020-10-03 11:16 UTC, NishkarshRaj commented on 9_Deep_Learning/Artificial_Neural_Networks/README.md
> +Finally, [**here**](https://www.youtube.com/watch?v=ILsA4nyG7I0&ab_channel=BrandonRohrer) is a video by Brandon Rohrer that explains the functioning of a neural network in the simplest and most intui
Links must be provided in References sub-topic. 
```suggestion
### References

[Deep Learning and Neural Networks](https://www.youtube.com/watch?v=ILsA4nyG7I0&ab_channel=BrandonRohrer) - a video by Brandon Rohrer that explains the functioning of a neural network in the simplest and most intuitive way possible.
```

2020-10-03 11:18 UTC, NishkarshRaj requested changes
Few suggestions:

* Mention links/referred material in a reference section in bottom.

* The images linked are on your repository called Resources and linked with absolute path.
Commit those images on this repository on `9_Deep_Learning/img` folder and then reference them via relative path like `img/filename.extension` rather than `github.com/username/filename`

2020-10-03 13:45 UTC, aceking007 commented
Cool. Working on it.

2020-10-03 14:04 UTC, aceking007 commented
> Few suggestions:
> 
> * Mention links/referred material in a reference section in bottom.
> * The images linked are on your repository called Resources and linked with absolute path.
>   Commit those images on this repository on `9_Deep_Learning/img` folder and then reference them via relative path like `img/filename.extension` rather than `github.com/username/filename`

Made all the changes. Added a few more resources to the references.  
Please review the changes.

2020-10-04 06:23 UTC, NishkarshRaj approved these changes
Great work @aceking007 😄 

Merged with master 👍

2020-10-04 06:23 UTC, merged